### ISSUE TITLE
Migrate to a multi-target project (feature request)

### ISSUE THREAD

**Issue by alexrainman** [couchbase/couchbase-lite-net#1027]
## Goals

Installing Couchbase.Lite 2.x in Android and iOS means installing a native library on each platform.

## Expected Results

A minimum set of packages to be installed in Android and iOS without installing .Net Standard SDK and other related dependencies, which makes package managing a mess.

https://montemagno.com/converting-xamarin-libraries-to-sdk-style-multi-targeted-projects/

https://montemagno.com/new-plugin-for-xamarin-multi-target-templates-for-visual-studio-2017/

## Actual Results

<img width="260" alt="screen shot 2018-05-26 at 8 54 03 am" src="https://user-images.githubusercontent.com/3793554/40578004-6db63c64-60d2-11e8-9abb-d3d5e154dde3.png">

**Comment by borrrden** [comment]
This looks like a symptom of using the old "packages.config" method of installing.  Here is a screenshot from the unit test runner which uses the "sdk style" method of installing the library:

<img width="288" alt="screen shot 2018-05-27 at 10 54 25" src="https://user-images.githubusercontent.com/2470288/40581801-65498f0c-619c-11e8-9c4e-05d88f21e9af.png">

**Comment by alexrainman** [comment]
I noticed that after installing the package in my net standard shared library, i can reference the assemblies manually, install the support packaged, call Activate() and everything works as expected so, Net Standard dependencies on platform specific projects are not needed.

A multi-target project can be the way to go.

**Comment by alexrainman** [comment]
I followed this steps:

- Installed Json.Net 11+ (which doesn't install any dependencies as you mentioned).
- Installed Couchbase.Lite 2.x

Same bunch of packages where installed, including Net Standard SDK 1.6.0, and you don't have a dependency on that version, it seems it is coming from SimpleInjector.

**Comment by alexrainman** [comment]
You already have these packages named Couchbase.Lite.Support.(platform). Maybe you can use them to distribute what is needed for the library to work in a "shared code" scenario where no business logic is developed in platform specific projects. It will behave more like a plugin and that's the way most of the developers use Xamarin.

**Comment by borrrden** [comment]
95% of the logic is cross platform C# that lives in Couchbase.Lite.dll (a .NET Standard 2.0 library).  If you want to try to use it plugin style then I suppose you could install Couchbase.Lite to your cross platform project, and just install the support package to your application project.  You won't be able to access any Couchbase Lite API from the application, though.  

I filed a downstream PR so that SimpleInjector has a NS2.0 version as well.  That should solve the long dependency list on old style projects (packages.config).

**Comment by alexrainman** [comment]
I tried that approach already but i get exceptions both Android and iOS

![screen shot 2018-06-01 at 10 50 56 am](https://user-images.githubusercontent.com/3793554/40850293-e58f4436-6589-11e8-9185-5b7fb8d316cf.png)

I tried changing the link behavior but that doesn't work neither.

**Comment by borrrden** [comment]
I saw an image in my email but I don't see it anymore here.  iOS can cause headaches because if there is no hard reference from app to assembly, the .net compiler will strip the reference and disable AOT compilation and inclusion....but Android is a bit surprising.  What happens there?

**Comment by alexrainman** [comment]
Android:

<img width="709" alt="screen shot 2018-06-01 at 4 56 50 pm" src="https://user-images.githubusercontent.com/3793554/40865507-2c6ef156-65be-11e8-8c58-a0bfbac1e082.png">

**Comment by alexrainman** [comment]
iOS:

![screen shot 2018-06-01 at 10 50 56 am](https://user-images.githubusercontent.com/3793554/40865517-37a166a8-65be-11e8-8d8e-e7a6ed2714d7.png)

**Comment by alexrainman** [comment]
Kind of the same error.

**Comment by borrrden** [comment]
I tried this out and hit the same error, but it went away after I added this to the .NET Standard project .csproj file inside the top `PropertyGroup`

```
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```

This property will cause things that usually live in the Nuget directory to be copied to the output directory.  Otherwise Xamarin is not smart enough to find them (at least on Mac).  

I still stand by my plans to not move to multi-target project.  The next version of SimpleInjector has accepted my PR and will include a .NET Standard 2.0 version so the original issue here should disappear.  I will close this issue now.
