### ISSUE TITLE
CBL logging written to stderr

### ISSUE THREAD

**Issue by mlynch** [couchbase/couchbase-lite-net#1131]
Currently, any logging from Couchbase Lite .NET is sent to stderr making it difficult/impossible to separate actual errors from informational logs.

This might very well be an issue in CBL Core instead of .NET but I wasn't sure.

### Library Version

2.1.2

### .NET Runtime

.NET Core 2.1.500
### Operating System / Device Details

MacOS Mojave

### Expected behavior

Non-error CBL logging should not be written to stderr

### Actual behavior

Non-error CBL logs should not be written to stderr

### Steps To Reproduce

1. Build a simple .NET Core app with CBL .NET 2.1.2
2. Run the app, notice the console output from CBL (such as Startup message and any logs set when using verbose log level) are sent to stderr

### Reproduction Project

Run the provided sample code in the CBL C# docs

**Comment by borrrden** [comment]
Well, logging was redone for 2.5 and there is a developer preview available so I'd suggest trying with that.  There is nowhere in .NET where I explicitly write to stderr but the default LiteCore logger will write to stderr for everything (I used to see this a lot back in the day for some reason...).  @snej Can you share the reason for writing everything to stderr by default?

Anyway I don't think the default logger is used for anything anymore in 2.5 since we made explicit interfaces for console, file, and custom logging.

**Comment by snej** [comment]
Writing to stderr is the generic, platform-agnostic way to log stuff. So that's what LiteCore's default logger (`LogDomain::defaultCallback`) does. But CBL should be setting its own logging callback to override that...

**Comment by borrrden** [comment]
I don't believe I do that on 2.1 because it seems wasteful to send messages down to LiteCore only to have them sent back across the managed / unmanaged boundary to do something that could be accomplished at the native level in the same way.  Iridium is another story and C# will be governing the console output.  If this needs to be ported back to 2.1.x then I'd like to add a method in LiteCore to go to stdout instead to save the above marshalling.

**Comment by djpongh** [comment]
@mlynch, any update on this?

**Comment by borrrden** [comment]
Closing due to lack of user response.
