### ISSUE TITLE
unsupported encryption algorithm

### ISSUE THREAD

**Issue by sriman94** [couchbase/couchbase-lite-net#1148]
Using couchbase lite enterprise edition 2.5 to evaluate. 

I have encrypted database which I disabled and tried to upgrade but it gave me unsupported encryption algorithm exception.

Tried with new database and the issue stays the same.

Kindly look into this and do the needful

**Comment by djpongh** [comment]
Are you upgrading from 1.x or 2.1.x?

If you are upgrading from 1.x, did you follow the steps in our documentation?

**Upgrading from 1.x when Encryption is Enabled**

If you’re migrating an application from Couchbase Lite 1.x to 2.x, note that the automatic database upgrade functionality is not supported for encrypted databases. Thus, to upgrade an encrypted 1.x database, you should do the following:

1. Disable encryption using the Couchbase Lite 1.x framework (see 1.x encryption guide)

2. Open the database file with encryption enabled using the Couchbase Lite 2.x framework (see database encryption).

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades. If you are using Sync Gateway to synchronize the database content, it may be preferable to run a pull replication from a new 2.x database with encryption enabled and delete the 1.x local database.

**Comment by Sandychuang8** [comment]
@sriman94 If instruction from @djpongh did not resolve the issue, would you please provide more information? You said you have encrypted database which you disabled. Would you please tell us which cbl version you were used to encrypt the database? And you said you tried with new database and the issue stays the same. Would you please provide detail steps and cbl versions you used for us to reproduce the issue?

**Comment by djpongh** [comment]
@sriman94 , do you have any more info for us?

**Comment by borrrden** [comment]
Closing due to lack of response
