### ISSUE TITLE
Implement LINQ IQueryable

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#245]

**Comment by zgramana** [comment]
Need to break this epic up into manageable issues.

**Comment by borrrden** [comment]
- [ ] all docs "select"
- [ ] map "select"
- [ ] map "where"
- [ ] map "orderby"
- [ ] reduce "aggregate"

**Comment by pkramerzoll** [comment]
@borrrden: Does this feature eliminate the need to provide an implementation for the map/reduce functions on a CBL View? I was looking through the merged changes, and it seems like the map/reduce functions are generated from the linq expressions for select/where/aggregate. Am I on the right track here?

**Comment by borrrden** [comment]
Yes, the LINQ implementation is designed to replace defining map and reduce functions.  You can see an example of how to use it [here](https://github.com/couchbase/couchbase-lite-net/blob/266c0970737ecc0e33211d3dff9e456457fb0346/src/Couchbase.Lite.Tests.Shared/ViewsTest.cs#L174) and [here](https://github.com/couchbase/couchbase-lite-net/wiki/LINQ)

**Comment by pkramerzoll** [comment]
Great, and thanks for the lightning response!

**Comment by alexrainman** [comment]
@borrrden i cannot use this from PCL. AsQuerable() doesn't exists. Which dependency im missing?

**Comment by borrrden** [comment]
I'm not sure what you mean. Couchbase Lite is not PCL compatible. The AsQueryable method is one I added post 1.3 and is currently only in CI builds.

**Comment by alexrainman** [comment]
@borrrden i am using it from PCL with no issues apart of this one. So AsQuerable is not yet released?

**Comment by alexrainman** [comment]
@borrrden i added the packages to android and ios and manually the references to pcl from net45 folder and it works

**Comment by alexrainman** [comment]
@borrrden also, whats the point of having something like this that has an assembly for net45 and not make it PCL compatible? That will be a huge disappointment :(

**Comment by borrrden** [comment]
There are a lot of APIs in use that are not available in any PCL profile (mostly due to Windows platforms). However the next step is getting UWP and .NET Standard 2.0 support.  See issue #535 for a discussion.

**Comment by alexrainman** [comment]
@borrrden there are things that are not available from PCL

```
throw new ApplicationException("Could not create database");
```

and

```
catch (CouchbaseLiteException ex)
```

My advice? make this PCL compatible with support for Xamarin.Android and Xamarin.iOS as these are the major platforms. UWP? you can release it in the future. It doesn't make sense not to do it now and need to wait for UWP compatibility.

**Comment by alexrainman** [comment]
@borrrden i am sure you are using "bait and switch" and all your third party dependencies are PCL compatible

```
Newtonsoft.Json
SharpZipLib.Portable
SQLitePCL.raw
SQLitePCL.ugly
Stateless
```

So, why not now? Who cares about UWP? :)

**Comment by alexrainman** [comment]
@borrrden and you are right, it works on Debug mode but not in Release.

**Comment by alexrainman** [comment]
@borrrden actually it works on Release also :)

**Comment by borrrden** [comment]
Well, mostly because I don't have a bait assembly (I would have to create one for each of the projects as well as the deps that I am compiling manually like websocket-sharp and it would burn through a lot of cycles).  Considering that it's already possible to consume Couchbase Lite in a portable way (via shared projects, which I admit is not the best) that time would be better spent refactoring the code for UWP, which would eliminate a lot of the problems with becoming an actual PCL.  The end goal is to become compatible with .NET standard (which is considered the replacement for PCL).  

You may think no one cares about UWP, but we receive many requests for it (more than PCL).  Windows tablets are becoming more and more widespread in the enterprise world.

**Comment by alexrainman** [comment]
I understand now your point and focus on enterprise. It was justa a phrase, i also offer UWP support in one of my projects because users asked for it and also, in my current job, we got our first UWP project request. We had a meeting with some of you co-workers today and we expressed two main concerns: PCL support and if its ok to use it adding the references manually and second, when Linq support will be released and i hope both things can be solved in a short time frame. Thanks
