### ISSUE TITLE
A simpler way of saving a domain object to a document (e.g. autoserialization)

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#275]
An email from bryan.hunter@fireflylogic.com

Hi Pasin, I'm curious if there is a simpler way of saving a domain object to a document than walking the properties, putting them into a dict, and then calling doc.PutPropeties(dict)?

Is there a slick autoserialization (e.g. Json.Net) way I am missing? 

Ideally I would say something like:

Person myPersonObject = db.Get<Person>(id);
...do stuff with it...
dd.Set<Person>(myPersonObject) 

or something like that and  everything would just work. I'm cool with doing this by hand, but i don't want to be a knuckle-head, if this already exists.

**Comment by milky-la** [comment]
Same here: very awkward that properties is unconditionally restricted to IDictionary without generic helpers to handle conversions. I would expand this request to also provide rawer api to be able to save and retrieve raw json: string and JObject versions.  

For retrieving documents, I can generalize my types T contruction with this
````
    JObject jobj = JObject.FromObject(doc.Properties);
    T obj = jobj.ToObject<T>();
````
This looks like an overkill because somewhere internally couchbase lite already deserializes json but into Dictionary, only for me to undo it back into JObject in order to get T or jsont string, that app really needs.

In case of updating documents, it's even worse because I need to write wrappers to convert already serialized JObject format into nested Dictionary<string, object>. 

For performance, the app could benefit if coubase didn't try to deserialize user properties in some cases at all. The app layer may need just the json string itself and not automatically deserialized representation.

Is there a more efficient or proper way to generially handle documents with custom types (not just dictionaries)?

**Comment by Dessix** [comment]
Is there still no way around auto(de)serialization? I just want to access the raw json of the objects...

**Comment by escamoteur** [comment]
I'm really stunned that this functionality is missing,  especially for a database that calls itself object centric. 
Any idea what is the best way to store c# objects at the current stage?  
Why can't I store json strings as documents?  that way I could use JSON.net for the conversion.

**Comment by borrrden** [comment]
We may move off of JSON at some point and move to a different serialization format so that's why we won't add raw json string CRUD operations.  That being said, this is one of the central focuses of our 2.0 API and so work will begin on it soon!

**Comment by wilsondy** [comment]
If I understand this correctly, this is more important now than before.  Before 2.x you could pass an object as a value in the dictionary, and json.net would be called for you on that object, so we could sort of get this to work sideways. 

Now, 2.x forcibly checks your values and kicks out object.

For complex Object graphs with 3rd party classes (preconfigured for json.net with their own Json.Net converters) this is a **major** roadblock.  I either have to a) serialize with json.net then deserialize, walk the tree and build up the dictionary, or b) reimplement my own serialization/deserialization including in and out of 3rd party classes.

**Comment by borrrden** [comment]
We now have an unofficial library that can handle this request until it gets scheduled as a feature of the library itself -> https://www.nuget.org/packages/Couchbase.Lite.Mapping/

However, I am closing this issue since it serves no purpose to just sit here.  We are tracking feature requests elsewhere.
