### ISSUE TITLE
Support for CBLReplication.pendingDocumentIds

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#473]
This feature has been implemented in iOS and was recently fixed to return the result even when the replication is not running. It's returned the document ids that haven't been pushed to the server.

Issue: couchbase/couchbase-lite-ios#807

**Comment by Steven-Mark-Ford** [comment]
I always get a null list when calling GetPendingDocumentIDs() on pull replication object. I took a look at the source and it seems _pendingDocumentIDs is never set in the case of a pull due to guard clause at the beginning of the GetPendingDocumentIDs method.

**Comment by borrrden** [comment]
That's by design.  This property is not supported for pull because the information is not available in the same way that it is for push.

**Comment by Steven-Mark-Ford** [comment]
Thanks. Do you know if there is any way currently to get the number of pending docs remaining to pull or if this is something that may be available in a future release? even if its a manually http request to SG.

**Comment by borrrden** [comment]
There are no plans for this functionality on either the cloud side or the client side.  The problem is the question "pending docs remaining for whom?".  Each replication, each user, each role has a different list of pending documents and they are calculated on demand and then streamed to the client.  If you can emulate the same call the `_changes` on Sync Gateway then you will be able to get the same information but be warned that this is a fairly expensive operation for Sync Gateway.  If you'd like to continue discussing this, however, consider using [our forums](https://forums.couchbase.com/c/mobile) so that other people can easily find it for reference.
