### ISSUE TITLE
Update/Replace replication filter

### ISSUE THREAD

**Issue by v3yr0n** [couchbase/couchbase-lite-net#488]
Hi!

Is there any way of update/replace the filter of a pull replication?
I'm stopping the replication, setting the new filter and start the replication. 
I've tried with restart too...

BTW, i'm purging the documents that i don't need before changing the filter.

Any help?

Thanks!

**Comment by borrrden** [comment]
The GitHub issues page is not for questions.  If you think you have an issue please write it as such, thanks.  Otherwise you can ask a question on our forums (https://forums.couchbase.com/c/mobile).  Anyway for anyone else who finds this ticket, please refer to here:

http://stackoverflow.com/questions/31971283/couchdb-update-replace-replication-filter
