### ISSUE TITLE
Push replication not pushing all expected documents when waking up

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#563]
Steps to reproduce using branch, transient-error-handler,  0e835a80a023f476078ca952b8dfa99dfd40d890

Steps to reproduce
1. Deploy CouchbaseSample.iOS 
2. Deploy SimpleAndroidSync
3. Point them to the same sync_gateway running 1.2.0(66;eb6fd21)
4. Create a couple items and make sure they sync
5. Take db offline, curl -X POST :4985/db/_offline 
6. Add some items on iOS client and let replication time out
7. Bring db online, curl -X POST :4985/db/_online
8. Wake up replication by checking on off the boxes for an item that was created while db was offline

Expected behavior:
Since the replication is awake, I would expect all the docs that were created when the db was offline would now sync

Actual behavior:
Only the item that was checked is sync'ed to the other client.

**Comment by borrrden** [comment]
@snej Need some insight for this problem.  I am not sure what the expected behavior is in this case.  From my reading of iOS native it looks like the change tracker should try forever while all other requests should give up after a couple tries.  This means that in theory the pusher would not be pushing new items but the puller would still be waiting for them.
