### ISSUE TITLE
Provision and run first test cluster p2p scenario locally

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#604]
Need to validate the local test work.

**Comment by jamiltz** [comment]
Based on the similar work done for Android here's some input and questions that apply to testcluster for Windows too:

- Based on a directory containing the `.exe/.dlls..`, how to run multiple instances of the app from the command prompt?
- Have a command prompt utility to start the Listener. Flags could be passed to perform different tasks (https://github.com/couchbase/couchbase-lite-ios/blob/master/Listener/LiteServ.m#L165-L181). Ideally, this would be part of the `couchbase-lite-net` repo and can be built from source as needed.

**Comment by borrrden** [comment]
I already have a command line listener set up for my own use as part of the repo.  I will modify it to include some flags

**Comment by borrrden** [comment]
Ok I added a .NET equivalent of LiteServ in commit be2ff52

**Comment by borrrden** [comment]
But I left in some unneeded junk in the run command arguments (when you press run in the IDE) so for reference of what I added, look at the commit I mentioned above but checkout commit 6e3b8c7

**Comment by borrrden** [comment]
@jamiltz Is there any information on how this test cluster will be set up?

**Comment by jamiltz** [comment]
Ok I'll give it a go. Well, I'm guessing that it depends on the platform so here's how it works on Android:

- The testcluster listener script installs the app on Android emulators or devices
- Configures port forwarding because Android emulators run in their own VMs
- Uses the CBL REST API to add docs/start and stop replications/delete the database

I would imagine that with the LiteServ CLI running on Windows, steps 1 and 2 won't be needed.

I think that with the command to start the listener on a specific port it should be enough to run similar tests to this one https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/functional_tests/android_listener_tests/test_listener_rest.py

**Comment by jamiltz** [comment]
With LiteServ for .Net available, the python client can spin up different instances of it and then run different p2p scenarios.
