### ISSUE TITLE
401 Unauthorized during replication

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#641]

**Comment by borrrden** [comment]
Details:  It has been reported that the replicator is not sending out cookies over the wire and this is causing 401.

**Comment by borrrden** [comment]
It turns out that this issue is actually different than I initially thought.  DateTimeKind needs to be explicitly specified or a mistaken double offset might be applied to the expiration date, making it mistakenly expired.  There is not much we can do about that but I'll add a warning if the datetimekind is unspecified, if possible, and a few other minor changes.
