### ISSUE TITLE
Delete replications not following the same behavior as the native iOS library

### ISSUE THREAD

**Issue by elements-of-boredom** [couchbase/couchbase-lite-net#656]
Specifically items with the _removed property are ignored in the changes feed in the .NET library. We do not see this behavior on the iOS client. The net result is deleting documents via sync gateway work correctly in iOS but not in .NET

Removing the return when the document was removed (code link below) appears to get us the same effect the native iOS library has in properly removing the document.
 
https://github.com/couchbase/couchbase-lite-net/blob/release/1.2.1/src/Couchbase.Lite.Shared/Replication/Puller.cs#L912

**Comment by andyast** [comment]
I believe I have a fix for this.  I could not find a reason why the code was checking for "removed" and then just exiting.  I removed this block and it worked in our tests.

    var removed = change.Get("removed") != null;
    if (removed) {
        return;
    }

Here is the branch with the change.
https://github.com/andyast/couchbase-lite-net/blob/DeletedDocsDon'tGetProcessed/src/Couchbase.Lite.Shared/Replication/Puller.cs#L911

**Comment by borrrden** [comment]
Removed and deleted are two different things.  Removed means that it was removed from a channel.  This sometimes happens if you don't check for deletions in your sync function when assigning channels (note that deletions will not have any properties available so it is likely that your channel assignments will fail in this case).  That will remove the item from the channel so the client will never receive permission to download the deletion.  

The reason removed entries are skipped is because there is no logic that needs to take place on the client side, and it can actually cause trouble.  The removed entry stores the last revision that the channel knew about, and this revision may not exist anymore (it could have been compacted away by either sync gateway or the body could have been evicted on Couchbase Server, resulting in a 404).  

Please double check your sync function and get back to me on that.

**Comment by borrrden** [comment]
@snej There hasn't been a change in this has there?

**Comment by snej** [comment]
@andyast is correct. CBL shouldn't be skipping removed items in the feed. It should download the new revision (which will just contain a `"_removed":true` property), which will correctly replace the earlier revision, so the document will appear to go away on the client side.

**Comment by borrrden** [comment]
I see.  I specifically made this change as a fix for a problem back in January so this makes me quite confused.  I remember though that the other part of the fix was the `active_only=true` setting so I think that will take care of things well enough to remove this.

**Comment by andyast** [comment]
Has there been a timeframe set for version 1.3 to be released?  This is a pretty big issue for us as our documents contain health information and leaving data on the device could create HIPAA concerns.

Thanks.

**Comment by snej** [comment]
I don't think we've set a public release date, but it's something like "a few months from now". In the interim, once Jim merges a fix for this issue you can cherry-pick the commit onto a tagged release and build your own library.

**Comment by pkramerzoll** [comment]
Also have the same requirement as @andyast.
