### ISSUE TITLE
Documents with null _attachments property cause NullReferenceException

### ISSUE THREAD

**Issue by andyast** [couchbase/couchbase-lite-net#657]
While it is not considered completely standard, null values are supported.  That being said if a document has a null _attachments property it will cause a NullReferenceException when attempting to push it.
Null reference exception occurs here:
https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Pusher.cs#L318

The issue stems from this check:
https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Pusher.cs#L505

I believe I have a fix with the changes here:
https://github.com/andyast/couchbase-lite-net/blob/NullAttachmentProperties/src/Couchbase.Lite.Shared/Replication/Pusher.cs#L367

and here:
https://github.com/andyast/couchbase-lite-net/blob/NullAttachmentProperties/src/Couchbase.Lite.Shared/Replication/Pusher.cs#L754

**Comment by borrrden** [comment]
Are you manually setting this property to null?  If so, stop that :p.  The underscore properties aren't meant to be messed with.  That being said, of course this behavior is undesired and I will fix it :).  If you aren't setting this property yourself then let me know ASAP because that is an even more undesired behavior!

**Comment by andyast** [comment]
Yes we were unintentionally setting this manually due to serialization settings server side.  Those have been corrected abe the sync works correctly without the null attachments property.
