### ISSUE TITLE
Unable to determine when a document is deleted or removed form a channel

### ISSUE THREAD

**Issue by pkramerzoll** [couchbase/couchbase-lite-net#670]
Issue #656 claims to resolve this, but after doing some testing I am still not able to detect when a document has been removed from a channel (or deleted completely). [This](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L939) code was recently changed to fix issue #656.

The return statement was removed, but the "removed" variable is not actually used anywhere (except to write a log entry), whereas the "deleted" variable is passed into the constructor of the PulledRevision on [this](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L964) line.

The "removed" value is in fact in the changes dictionary and it is "true" as expected when a channel is removed from the document. When checking the "IsGone" property of the revision when the Document Change event is handled, it is always false.

**Comment by borrrden** [comment]
Right, that value won't be used.  Instead it will try to get the document as usual, and the `_removed` property should have been added by Sync Gateway (or, if the body is not available it will be a 404 and skipped, but this should be a very rare case and is the reason for the `active_only` mode for the initial sync).  What happens if you try to request the document in question from Sync gateway with the ?rev=<revid> parameter?

**Comment by borrrden** [comment]
Also, if IsGone is false, that means that the `_removed` entry is not there.  If you retrieve the document natively can you check the properties?  You might have set up a replication that still has access.

**Comment by pkramerzoll** [comment]
Perfect, thanks for the hint. Looks like it was exactly what you stated; I still had access to one of the document's channels. Once I moved the document to channels that my user did not have access to, the "IsGone" property returned the correct value.
