### ISSUE TITLE
Xamarin Linking Fails if Project does not target API 23

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [couchbase/couchbase-lite-net#711]
I get the following linker error if I try to build my project using the latest couchbase 1.3 release.
The project is currently targeting API 19 I can only get rid of this message if I target API 23 which our project is not yet ready for. 

Is there a way around this without updating the target sdk to 23?

```
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1616,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.

C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1616,5): error MSB4018: Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item 'Android.Security.Keystore.KeyGenParameterSpec' (defined in 'Couchbase.Lite, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null') from 'Couchbase.Lite, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Security.Keystore.KeyGenParameterSpec
```

**Comment by borrrden** [comment]
Is this "target" or "compile".  You need to compile with API 23, but you can target back to API 19.

**Comment by Steven-Mark-Ford** [comment]
When configuring a project via visual studio project window it has validation to ensure the compilation and target values are equal. I can get around this by manually updating the manifest.

**Comment by borrrden** [comment]
Oh I'm thinking of the "minimum" android version.  There are too many versions for me to keep track of...

I think Java imposes this restriction (the target value means that apps or libraries that build against it must use the same or higher), but you say you are able to get around it?  I need to compile with the newer compiler because there was a change in API in 23 that we are taking advantage of (ability to store AES keys in the system keystore).  For the sample app I currently have target at "latest" and minimum at 10.  If you are making a library you will only see one (target).  

Is there something that has changed that makes you unable to target 23 (removed / changed API or something?).  Otherwise lower Android operating systems will still be able to use it even if you target 23.

**Comment by Steven-Mark-Ford** [comment]
I'm not ready to update the apps target sdk to 23 so I will manually set the target to 19 in my manifest but make the compile sdk 23. by manually setting the target in manifest I can get around the limitation visual studio project window is imposing by forcing me to set the target sdk to the compile sdk. I know setting target=compile sdk is ideal but I do not want to do this yet. I am happy I can now link against CB. so non-issue here and happy if you close this

**Comment by borrrden** [comment]
Alright, I'm glad things have worked out!
