### ISSUE TITLE
Support for _oidc_refresh response without ID token

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#714]
https://github.com/couchbase/couchbase-lite-ios/issues/1400

**Comment by pasin** [comment]
I have verified that there is no code change on iOS and Android. I expect the same for .NET. Could you please verify SGW changes by using Grocery-Sync .NET with the oidc_test_provider by following these steps?

1. Download sync-gateway 1.3.1-10 (http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.3.1/1.3.1-10/)

2. Setup Couchbase Server with grocery-sync bucket so that we can blow away user's sessions documents easily from its admin UI. SGW /DELETE /{db}/_user/{name}/_session seems to have an issue deleting user's sessions so I couldn't find an easy way to delete the user's session.

3. Configure SGW config pointing to Couchbase Server from Step 2.

4. Configure oidc_test_provider in the SGW config with  `"unsigned_id_token": true` added to the `oidc_test_provider` in the `unsupported` section. Also make sure to make the test provider as the default provider.

 ````
 "unsupported": {
    "oidc_test_provider": {
          "enabled": true,
          "unsigned_id_token": true
     }  
 },
 ``` 
 See the complete sample config file here: https://gist.github.com/pasin/633f9242f699600b11748a8d108695e6#file-oidc_sgw_config-json.

5. Start SGW

6. Run Grocery Sync app and login to OIDC test provider. Type username and make sure the app login successfully.

7. Shutdown the app.

8. Open Couchbase Server Admin UI, go to grocery-sync bucket, and delete the user's session doc. The session doc ID begins with `_sync:session:`.

9. Run Grocery Sync app again and login to OIDC test provider. 

 - Verify that the user are able to login **without** retyping username. 
 - Verify that the refresh token flow was executed. On SGW log, there should be something like this:
```
2016-08-23T11:30:28.885-07:00 HTTP:  #017: GET /grocery-sync/_oidc_refresh?refresh_token=******
2016-08-23T11:30:28.886-07:00 OIDC+: GetProviderForIssuer with issuer: http://10.17.2.133:4984/grocery-sync/_oidc_testing, audiences: [sync_gateway]
```

**Comment by borrrden** [comment]
@pasin  Couldn't you just restart sync gateway to blow away the session?

**Comment by borrrden** [comment]
Anyway I tried this out with my attempt at building Couchbase Server 4.5 (but it reports 4.0....).  I was able to verify the same steps using the 1.3.1 release branch.  So since this requires no change I am going to remove the milestone and close.
