### ISSUE TITLE
Improve the build notes.

### ISSUE THREAD

**Issue by mcpaddy** [couchbase/couchbase-lite-net#726]
This was noted by a user on IRC: 

>06:29 < connor_goodwolf> does anyone have instructions to complie couchbase-lite-net? None of the solutions work out of the box with mono studio or visual studio. I did perform a git submodule update --init --recursive. It's complaining about CBForest dlls
>06:32 < connor_goodwolf> holy [crap] why doesn't CBForest build automatically? This is retarded if I've to compile it separately
> 15:31 < connor_goodwolf> macpaddy: the instructions need to be more clear. I tend to work on a variety of technologies.
> 15:31 < connor_goodwolf> macpaddy: I was [messing] around with all this [crap] over a day

Reviewing the [building-couchbase-lite-master-branch-from-source](https://github.com/couchbase/couchbase-lite-net#building-couchbase-lite-master-branch-from-source) in the README, the steps seem a little backwards. Given that forestDB is a prerequisite I would expect that to be the first step.

It would be great in the long term if couchbase-lite-net pulled in forestDB and build it automatically.

**Comment by borrrden** [comment]
That is unlikely to happen given that it is not C# (How can I be sure the user has xcode, make, etc?).  You don't have to build it yourself unless you are changing something, otherwise you can download precompiled binaries from the CBForest repo.  Also, ForestDB is not a prerequisite.  It isn't needed for compiling Couchbase Lite.  It will build if you build the solution, but if you just want Couchbase.Lite then you only need to compile the Couchbase.Lite project and storage-system-sqlite.  Everything else is optional.
