### ISSUE TITLE
ForestDB Failure to delete database (500)

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#816]
http://uberjenkins.sc.couchbase.com:8080/job/net-windows-listener-client-sync-gateway/153/console:
 
>       client.delete_databases(ls_url)
E           HTTPError: 500 Server Error: Internal error for url: http://172.23.121.129:59840/ls_db
 
>       raise LiteServError("There should be no service running on the port")
E       LiteServError: There should be no service running on the port
 
>               raise keywords.exceptions.TimeoutException("Verify Docs Present: TIMEOUT")
E               TimeoutException: Verify Docs Present: TIMEOUT

**Comment by borrrden** [comment]
This has been determined to be an environment issue.  I will close all the tickets before this as duplicates and leave this one open until we figure out what to do about it.

**Comment by sethrosetter** [comment]
https://gist.github.com/anonymous/cdb576ffe025fdee0e9f74fc672730ae

**Comment by sethrosetter** [comment]
I saw it with `test_client_to_sync_gateway_complex_replication_with_revs_limit` 

```
pytest -s --liteserv-platform=net-msft --liteserv-version=1.4-43 --liteserv-host=192.168.0.57 --liteserv-port=5000 --liteserv-storage-engine=ForestDB --sync-gateway-version=1.3.1-16 --sync-gateway-mode=cc --server-version=4.5.1 testsuites/listener/shared/client_sg/
```

**Comment by borrrden** [comment]
Alright, this is a race condition that we will have to live with for 1.4 because we are too close to the deadline to make the kind of dangerous changes needed for this.  If we have a 1.4.1 it will go into there, but basically if you are doing a lot of REST API calls to a database, a delete will not be atomic and so another connection will open it between the "close" and "delete" operations of the delete request.

**Comment by djpongh** [comment]
Will not be getting to this.
