### ISSUE TITLE
Using in UWP

### ISSUE THREAD

**Issue by mohsens22** [couchbase/couchbase-lite-net#833]
Hey
I want to use couch base and sync gateway in my UWP project. I read #535 and seems that you are working on it and some code are available for compile.
How can I get and compile them? I can do some commits where needed.

**Comment by borrrden** [comment]
See [this page](https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/index.html) on the .NET tab.  You just need to add our developer build feed to your sources.

**Comment by mohsens22** [comment]
Is there ant UWP support ?

**Comment by borrrden** [comment]
Indeed, there is.  For some reason it doesn't seem that Nuget will automatically download the dependency (Couchbase.Lite.Support.UWP) so make sure that one is also added, and call `Couchbase.Lite.Support.UWP.Activate()` at the application launch.  It seems the documentation I wrote about that has disappeared from the website...I'll have to put it up somewhere again.

**Comment by mohsens22** [comment]
Which solution shall I compile?

**Comment by borrrden** [comment]
I gave instructions for getting a built one from our Nuget source.  If you want to build from source you will need to check out the `feature/api-v2` branch.  Everything is there in the Couchbase.Lite solution (you will need to build Couchbase.Lite, and Couchbase.Lite.Support.UWP)

**Comment by mohsens22** [comment]
![image](https://cloud.githubusercontent.com/assets/22152065/24317179/6cca3a3c-1112-11e7-8110-37f5b2f2e22b.png)

A couple of projects failed to load :/

**Comment by borrrden** [comment]
It looks like you didn't check out the submodules (`git submodule update --init --recursive`) which is why the bottom one is reported as missing.  

The other one I am not sure about.  Is this Visual Studio 2017 with .NET Core tooling installed?

**Comment by mohsens22** [comment]
![image](https://cloud.githubusercontent.com/assets/22152065/24321794/e752e294-1172-11e7-88c7-ffccd7dd4def.png)
What to do with this error ? :(

**Comment by mohsens22** [comment]
Please send me instructions to use Couchbase in UWP.
I use it till I could compile :)

**Comment by borrrden** [comment]
I've never seen that error message before but a quick google search says to install the modeling SDK for visual studio. I don't like that requirement (I didn't know it existed) and I will look into other ways to do text templating that don't have that requirement but for now it looks like you need to install that into your dev environment (I don't remember installing it so that is a bit odd).   We don't have a whole lot available for code samples because the 2.0 API is under initial development, but have a look at the unit tests in the src/Couchbase.Lite.Tests.Shared folder to get an idea and also check out the docs I linked above. The API is subject to change and open for suggestions before it's release around July.  If you just want to get started quickly then follow the instructions I linked in my previous comment to install the prerelease Nuget packages.

**Comment by LittleStar9637** [comment]
Hi
I'd like to make xamarin uwp app with couchbase, I read [this](https://github.com/couchbase/couchbase-lite-net/issues/535) and I checked [this page](https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/index.html)
I'm not sure, does the sdk exit?

**Comment by borrrden** [comment]
@LittleStar9637 I don't understand your question.  The page you linked to says how to get the Nuget package.  Also what do you mean by "Xamarin UWP".  Do you mean "Xamarin and UWP"?  "Xamarin UWP" doesn't make sense because they are two different technologies.  Also, questions like these are better suited for the [forums](https://forums.couchbase.com/c/mobile) in the future.

**Comment by djpongh** [comment]
Jim's right, this is really a question for the forums unless an issue is found.
