### ISSUE TITLE
Couchbase.Lite.dll missing Product Version Info and Others

### ISSUE THREAD

**Issue by pkramerzoll** [couchbase/couchbase-lite-net#840]
When viewing the Windows properties page for Couchbase.Lite.dll, the fields for product name and version, and file version are empty. However, the assembly itself appears to be version 1.4.0.0.

The missing product version information is causing Windows Installer to not be able to do an in-place upgrade of Couchbase.Lite.dll from version 1.3.1 to 1.4.0.

The 1.3.1 of the same assembly contains this information.

![v1.3.1 Screenshot](https://cloud.githubusercontent.com/assets/18703746/24779580/94455ae8-1aee-11e7-88ac-52284d9b8525.png)

![v1.4.0 Screenshot](https://cloud.githubusercontent.com/assets/18703746/24779644/f14bdb5e-1aee-11e7-8cfb-f99b87d375aa.png)

**Comment by borrrden** [comment]
This is the result of my tool not rewriting this stuff, and it's actually pretty hard to write (uses archaic Windows functions from back in the Excel glory days) so instead I think I will not touch the assembly.  I will leave the info as it is for the next release which means that Product Version will be 1.4.1-b080 (for example, the build number is not finalized) instead of 1.4.1.  File Version will be 1.4.1.0.  I don't really decide these values, by the way.  They are written by the .NET compiler from the assembly attributes.
