### ISSUE TITLE
Investigate UWP WACK violations

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#859]
Casually deciding to run WACK (Windows App Certification Kit) has made me realize that there are rampant violations of the disallowed C / C++ APIs in use.  Hooray for that, because everything runs just fine and this just serves to make cross platform development even more fragmented.  However, I will need to refactor the Windows native DLLs into a build for .NET Core, and a build for UWP because they will have separate requirements.  This also means that .NET Core will get its own "support" library so that it is possible to choose between two different WIndows native DLLs in a sane way.  This will likely take multiple days of work.

**Comment by mohsens22** [comment]
@borrrden 
Disallowed APIs can be used in some cases and "WACK" won't have problem with that. I remember a DEV told me you can use it with a certificate from Microsoft. Because in one of my projects I used one of them and after contact with MSFT they told my that I should clarify usage and sent report to MSFT and then get an enterprise account then I could use those APIs. Also I see a lot of apps in store that they use disallowed APIs (as an example, What's app uses a file picker in WP8 which the API is disallowed).
You can solve this problem in ways.
I think @NGame1 can help you with that.

**Comment by borrrden** [comment]
Interesting.  There were quite a few of them (100-200+) and they really did not make sense to me though...things like `memcpy` and `iostream` were flagged as disallowed.  I'm trying to figure out if those are real or not.  If I can avoid it I'd prefer not to have them so that users don't have to jump through hoops to get apps onto the store.

**Comment by mohsens22** [comment]
Yes, Try to fix it from the bone :D

**Comment by borrrden** [comment]
It looks like I needed to include the Visual C++ 2015 runtime component since the native components are compiled with VS 2015.  After I did that, WACK only reports violations from two DLLs that are not mine:

vstest_executionengine_platformbridge.dll
vstest.executionengine.WindowsPhone.dll
