### ISSUE TITLE
2.0 DB #10 on UWP: DateTime property comes back as String

### ISSUE THREAD

**Issue by rainerg2000** [couchbase/couchbase-lite-net#877]
I am evaluating CB Lite .net in a Windows UWP application. When I read a document that has a DateTime property, I see that `Couchbase.Lite.Document.ToProperties()` returns a string instead of a DateTime.

Here's how I write the object to the DB: 
```
var testEntity = new SimpleEntity 
{ 
  Bool1 = true, 
  DateTime1 = new DateTime(1977, 5, 4), 
};
var asDict = new Dictionary<string, object>(); 
foreach (var field in JObject.FromObject(testEntity)) 
{ 
  asDict[field.Key] = field.Value; 
}
var newDoc = new Document(docIdToCreate, asDict); 
mDB.Save(newDoc);
```

Here's how I read back the object: 
```
var doc = mDB.GetDocument(existingDocId); 
doc.ToDictionary(); 
```

Now I see 
`doc["DateTime1"] ` is of type string.

On the other hand in CB Lite .net 1.4.1 on Android I see that `doc["DateTime1"]` is of type DateTime.

**Comment by borrrden** [comment]
Can you use `DateTimeOffset` instead?

**Comment by borrrden** [comment]
Also, this is not the preferred way to access the properties.  One of the focuses is getting information out of a document without converting to a dictionary first.  So instead you can do `doc["DateTime1"].ToDate()`.  I'm not sure if the method you mentioned is possible because no type information gets saved with the information to the disk.
