### ISSUE TITLE
Public TxtRecord class

### ISSUE THREAD

**Issue by FernandoMorais** [couchbase/couchbase-lite-net#886]
Hi guys!

I'm working on a project that uses a Bonjour with some aditional data in Txt Records.
Is there something that caused you to change the class `Mono.Zeroconf.Providers.Bonjour.TxtRecord` to `internal`?

Whould be better if it was `public`.

**Comment by borrrden** [comment]
The bonjour component is deprecated so I wouldn't recommend its use at this point.  It would be better to simply use platform specific solutions to do the discovery since Bonjour is of very questionable usefulness at all...

That being said I don't remember much about why I did what I did since the last time I touched that code is probably at least 1 year ago.
