### ISSUE TITLE
Xamarin.iOS fails to compile if linking is enabled

### ISSUE THREAD

**Issue by zippo227** [couchbase/couchbase-lite-net#888]
I've raised this issue with Xamarin, but they think that it might be related to the way Couchbase.Lite is built. I don't really know, but I've been working on this for over a month and need it to work. Here is a link to the bugzilla bug. https://bugzilla.xamarin.com/show_bug.cgi?id=57124

Here is a sample project that fails to compile in Release.
https://github.com/zippo227/ios-samples/tree/master/ios10/MessageCodeSharing

**Comment by zippo227** [comment]
According to @jbevain , "... it might be the case that the Couchbase nuget ships a broken mdb." You need to push out a new nuget.

**Comment by jbevain** [comment]
I haven't investigated the full project, so I don't have a definitive answer on where the issue is. Point is, the Xamarin linker was received a set of `dll` + `mdb` debug symbols, which I think are from the Couchbase NuGet, where the MDB was out of sync with the `dll`.

It's easy to verify with Mono's `mdbdump` tool, and see if the number of sequence points or variables don't match with a `ildasm` dump of the dll.

**Comment by borrrden** [comment]
@jbevain Would an older version of Xamarin IOS possibly cause this?  I don't have access to the machines that build (that's another team's realm) and so I've been sticking with the same version for a long time now (back when Xamarin Android 6 was new).  I simply add both the dll and the mdb file that get generated during the build, so I'm not sure how they could get messed up.

For 2.0, things are a lot better in that area however.  2.0 is our priority at the moment and 1.x work is for emergencies only (i.e. an enterprise support ticket) until management says otherwise.

**Comment by zippo227** [comment]
@borrrden I understand the need to push forward to 2.0. It could be the case though that you are sabotaging yourselves by sending a large portion of your userbase into searching for other alternatives. I would suggest you get the latest version of Xamarin.iOS on the build server and recompile the nuget packages, distributing them as 1.4.1. For me personally, I hand-compiled them with the latest version, and they are working.

**Comment by borrrden** [comment]
I understand that argument but we cannot simply push things out like that. There is a long process we have to go through and all of our resources are tied up right now. Another thought would be to delete the mdb file from the Nuget package after it is downloaded and see if that helps.

**Comment by borrrden** [comment]
Update: I've been put back onto an official 1.4.1.  I will get the components updated asap.

**Comment by borrrden** [comment]
I filed an internal ticket to get our 1.x build server upgraded.  Hopefully it goes smoothly since I think it is still using El Capitan, Xcode 7-ish, etc.  The last time we rebooted the server it took hours to get it to work properly again so here's hoping!

**Comment by borrrden** [comment]
@zippo227 http://latestbuilds.hq.couchbase.com/couchbase-lite-net/1.4.1/106 This was built with a newer version of Xamarin.  Let me know if it resolves the issue.

**Comment by zippo227** [comment]
@borrrden  Since we ended up compiling it ourselves, we haven't needed the update. I'll try and take a few minutes tomorrow in a separate branch to see if your new fix works. At this point I barely remember exactly what the issue was.

**Comment by zippo227** [comment]
@borrrden  Ironically, the exact same code and package combination now compiles with the latest version of Xamarin. So it seems their newest code is more robust at handling a broken mdb. I was not able to install your latest nuget package in my visual studio for mac (the source was not recognized), but the problem seems to be fixed without it.
