### ISSUE TITLE
Channel removal potentially disrupts attachments

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#910]
In the following scenario, attachments will not be able to be found:

1. Client goes offline
2. Attachments are added to the document
3. Channel removal happens and the client loses access to the document
4. Client comes online and receives the removal (since there are no attachments on a removal the client assumes there are none at all)
5. Client regains access and discovers that there are attachments, and searches for them.  However it won't find them because it will only check back to the last known revision (the removed one)

**Comment by snej** [comment]
To be precise, I think the last steps are:

5. The server gets a new revision that gives this client access to the document again
6. Client pulls this revision, requesting attachments since (`atts_since`) its previous revision (the removal), of which there are none.
7. Client looks for the attachments but doesn't have them.

The bug is that in step 6, the client should have requested attachments since the _previous_ revision it had when it went offline, i.e. the one before the removal stub.
