### ISSUE TITLE
Conflict resolver fails to write server version of document

### ISSUE THREAD

**Issue by mr-jingles** [couchbase/couchbase-lite-net#918]
Hi,

I have a question regarding the Conflict Resolver - I am running:
- Couchbase Sync Gateway/1.5.0(494;5b6b5b9)
- Walrus DB
- CBL 2.0 db014

Currently when a conflict is registered by the Conflict Resovler the  resolve method is called. If I return "conflict.Theirs" the local DB Entry will not change to the Server Version. 
What actually happens is that my local change will get pushed to the server. The _changes endpoint shows that I now have two revisions of this document.
According to the CBL Documentation my Document is now in conflict state. I expected the loosing Revision "conflict.Mine" to get the _deleted:true" flag. Am I missing something obvious? Do I have to call the delete of the loosing revision manually? And if so how can I retrieve the _rev of the document. A select via  SelectResult.Expression(Couchbase.Lite.Query.Expression.Property("_rev") is not returning anything fom the database.

**Comment by mr-jingles** [comment]
I also see an issue with the current conflict resolver example:
https://github.com/couchbase/couchbase-lite-net/pull/896#issuecomment-336841161

**Comment by borrrden** [comment]
It's a bit hard to understand what is going on here without a simple example showing what you are trying to do.  The conflict resolver will always create a new revision, and old ones will not be deleted nor do they need to be.  The new revision will simply override the old one. It's not the same as resolving conflicts in 1.x.  We made a decision to preemptively resolve conflicts before they happen since the biggest source of confusion other than how to use views was how to deal with conflicts (in fact most people didn't even realize they were creating them).  So you aren't resolving an *existing* conflict with the resolver, but rather *preventing* one by telling the library how to move forward with the next normal revision given two or three inputs.

**Comment by mr-jingles** [comment]
Hi borrrden,

thank you for your response. I attached a little console program which should reproduce my issue and the steps I have taken.

In the end my problem is even when the conflict resolver is called an I return the server version.
The local database will still have the local change as the winner when I query the document. And my local change will get pushed to the server leaving the document on the server in a conflict state with two revisions. The winning revision on the server is always case 4:

_Case 4: There is a tie
The winner is the one whose revision ID sorts higher in a simple ASCII comparison_

Taken from the documentation here: https://blog.couchbase.com/conflict-resolution-couchbase-mobile/

[Issue918.zip](https://github.com/couchbase/couchbase-lite-net/files/1390521/Issue918.zip)

**Comment by borrrden** [comment]
Whoa!  This is actually a bug that none of the tests picked up.  It's a bug in the autogenerated C bindings.  This means that whenever you choose the server version directly as the winner it will throw and log an exception.  Since it happens during replication there will need to be a functional test written for it instead of an automated test, so that will come later but for now I've fixed the example you gave.  The fix will be in DB019.

**Comment by mr-jingles** [comment]
Thanks borrrden for making this product better every day! :)
