### ISSUE TITLE
Signed Assemblies

### ISSUE THREAD

**Issue by badavid85** [couchbase/couchbase-lite-net#935]
Hi.

I am using Couchbase.Lite 2.0.0-db019, and I would like to know if you guys plan to sign the assemblies with Strong Names at some point.

Thanks.

**Comment by borrrden** [comment]
I've been down this road before, but signing assemblies seems to cause nothing but pain for me without much visible benefit.  Signing was mostly beneficial for the GAC, which is now more or less deprecated.  I tried to sign the DBs before but then suddenly `InternalsVisibleTo` broke for some platforms and I need that for testing.

If someone (probably would have to be a paying customer) presents a compelling reason though, of course I will reconsider.

**Comment by badavid85** [comment]
I have had some issues when using `InternalVisible` targeting strong-named assemblies and I was able to fix them by providing the PublicKey instead of PublicKeyToken.
`[assembly: InternalsVisibleTo("MyAssembly.dll, PublicKey=...")]`
This key is generated by using the `sn -Tp` command.

If you provide me the details of the issues you had, I might be able to help and PR it back to you.

By the way, we are a paying customer 😄, I could work on some compelling reason if needed.

**Comment by borrrden** [comment]
Ok then hit me with a good reason then.  So far what I can see is that people say it is to "prevent tampering" (which doesn't really work unless the runtime enforcement is turned on I think).  The issues I was having before was InternalsVisibleTo simply didn't work with .NET Core.  It would always fail with the inaccessible API compiler error, despite using PublicKey instead of PublicKeyToken (I was using extended signing to get access to SHA-256 instead of SHA-1)

**Comment by borrrden** [comment]
Also see this quote from [Microsoft](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md)

> For the most part, the majority of applications and libraries do not need strong-names. Strong-names are left over from previous eras of .NET where sandboxing needed to differentiate between code that was trusted, versus code that was untrusted. However in recent years, sandboxing via AppDomains, especially to isolate ASP.NET web applications, is no longer guaranteed and is not recommended.

I just tried again to do this with .NET Core and was again met with the `InternalsVisibleTo` not working problem.  Maybe it only works when not doing delayed signing?

**Comment by badavid85** [comment]
Thanks for your reply.

This is one of the reasons for me to ask you to sign the assemblies:
For Windows Desktop Apps (In my case a WPF App), if you enable ClickOnce Deployment, the build will fail:
Error Assembly 'C:\Users\Bruno\.nuget\packages\couchbase.lite\2.0.0-db019\lib\netstandard1.4\Couchbase.Lite.dll' must be strong signed in order to be marked as a prerequisite.

ClickOnce is an important mechanism for us to safely distribute and manage versions on occasionally connected desktop client computers.

**Comment by borrrden** [comment]
I know of some MSBuild tasks that are available that can [sign already compiled assemblies](https://github.com/martinkirsche/StrongNameResigner).  Without being able to get around the testing issue, I am not keen on signing because that will mean that the signing will have to occur after all the testing is done, which modifies the product that was tested.  That makes me nervous, despite the low chance of it affecting anything.  

I assume that clickonce has everything needed already put together (i.e. the end user does not use Nuget?) so I think a workaround for your case could be to make use of the tool I mentioned to sign the Couchbase Lite assemblies along with yours for packaging.

**Comment by badavid85** [comment]
I will find some time to build it locally and try to add Strong Names.... unless you are planning to add it on the next build....

**Comment by borrrden** [comment]
I tried this again recently with the same results:

If I am building from project references then I can use `InternalsVisibleTo` but once it is inside a nuget package (Our automated and functional testing is based on a packaged version) it will falsely claim that it cannot access the internal API.

**Comment by borrrden** [comment]
From [.NET Documentation](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries)

✔️ CONSIDER strong naming your library's assemblies.

✔️ CONSIDER adding the strong naming key to your source control system.

This suggests that we should just take this and do it the easy way (I'll have to check again via nuget package to see if that bug is still present)

However:

❌ DO NOT add, remove, or change the strong naming key.

Modifying an assembly's strong naming key changes the assembly's identity and breaks compiled code that uses it.

So this will have to wait until the next major release.

**Comment by borrrden** [comment]
@badavid85 Were you able to work with a mechanism that signs prebuilt libraries?

**Comment by badavid85** [comment]
Haven't had a chance to get back to this issue.
I understand strong naming assemblies is a bigger discussion, even on .net core's GitHub.
You may close it if you want for now and I can re-open it in case I decide to get back to it.
Thanks

**Comment by djpongh** [comment]
Ok, closing...
