### ISSUE TITLE
CB 2.0, DB 21, Could not find LiteCore.dll

### ISSUE THREAD

**Issue by peresbruno** [couchbase/couchbase-lite-net#949]
I'm trying to use CB 2.0, DB 21 in a .NET class library project unit test (.NET Framework v4.6.1). The code that I'm using to create a database is the following:

    Couchbase.Lite.Support.NetDesktop.Activate();
    var db = new Database("database");

But in the first line I'm getting the error `Could not find LiteCore.dll!  Nothing is going to work!`. What I'm doing wrong?

Steps to reproduce:
 - Create a unit test project.
 - Create a test method
 - Add the above code snippet
 - Run test method 

My environment:
 - macOS 10.13.2
 - Rider IDE 2017.3

**Comment by borrrden** [comment]
I've never used Rider before, and so I find the notion of ".NET Framework 4.6.1" on mac to be a dubious one.  That is not one of our supported platforms.  Mac is supported via .NET Core officially.  That being said, I don't see a technical reason why this should not work.

It seems like your code is entering a windows-only path (i.e. guarded by `RuntimeInformation.IsOSPlatform(OSPlatform.Windows)`).  If that is the case then something is wrong with Rider, or the environment that it installs.

**Comment by borrrden** [comment]
Also, that error message seems a bit sparse.  It should indicate the locations that were tried.  Part of me thinks that there are two projects here with potentially two different versions of Couchbase Lite on it.

**Comment by peresbruno** [comment]
Let me give to you some more details about my solution. I'm working in a Xamarin.Forms app. My solution has 4 main projects, as listed below:

 - A Xamarin.Android project: in this project I'm calling `Couchbase.Lite.Support.Droid.Activate(this);` in the `MainActivity.OnCreate` method.
 - A Xamarin.iOS project: in this project I'm calling `Couchbase.Lite.Support.iOS.Activate();` in the `Main` method.
 - A .NET Standard 2.0 project, for code sharing.
 - A NUnit project, targeting .NET Framework v4.6.1

When I run my solution in a device I can create a database calling `new Database("database");`. It works because the appropriate `.Activate` method is being called in the native project before the `new Database("database")` call.

However, when I try to create a database inside my NUnit project, it is throwing the exception `System.DllNotFoundException : Could not find LiteCore.dll!  Nothing is going to work!` in the line `Couchbase.Lite.Support.NetDesktop.Activate();`, before the `new Database` call.

Maybe it is only a path problem. The stack trace gives me the following information:
```
Tried searching in:
/Users/brunoperes/projects/ColetumAppV2/ColetumApp.UnitTests/bin/runtimes/win7-x64/native/LiteCore.dll
/Users/brunoperes/projects/ColetumAppV2/ColetumApp.UnitTests/bin/Debug/x64/LiteCore.dll
/Users/brunoperes/projects/ColetumAppV2/ColetumApp.UnitTests/bin/Debug/bin/x64/LiteCore.dll
```

I have tested in Visual Studio for Mac and getting the same output.

I'm sorry, I'm newbie in the .NET platform. Maybe I'm asking a dumb question.

**Comment by borrrden** [comment]
The troubling thing is that the path you mention is only meant to be executed on Windows, as I mentioned before.  It indicates a flaw in the .NET runtime, which is why I was asking about which runtime is being used.  "NUnit on .NET Framework 4.6.1" does not make sense in this context because .NET Framework 4.6.1 is a Windows-only environment.  Perhaps it is an *emulated* .NET Framework 4.6.1 environment (running via mono) in which case that is not supported.  

There are two things that can help narrow this down:
1. What is the output of `System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.Windows)`?  If it is true, then things are busted for your setup.
2. Does a .NET Core app work?
3. Is it possible to try out ".NET Framework 4.7.1" instead to see if that changes anything?

I had a look at the [API page](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform?view=netframework-4.7.1#System_Runtime_InteropServices_RuntimeInformation_IsOSPlatform_System_Runtime_InteropServices_OSPlatform_) for this call, and it says it is only available in .NET Framework 4.7.1 (which is weird considering that it is available in .NET Standard 1.1...) so maybe that's the reason.

**Comment by borrrden** [comment]
Yes, it seems the issue lies with .NET 4.6.1 via mono so there is nothing left to do on this ticket.  I will close it.
