### ISSUE TITLE
Confused about .NET Standard support

### ISSUE THREAD

**Issue by opcodewriter** [couchbase/couchbase-lite-net#961]
I added "Couchbase.Lite" 1.4.1 from NuGet to a .NET Standard 2.0 library and it shows warnings 
![image](https://user-images.githubusercontent.com/15019084/35989939-285a9b58-0d0b-11e8-9a07-e66e1ed52d65.png)

I tried to search for information, but it's not clear to me if this is supposed to work or not.

Just by looking at the dependencies it doesn't seem to work with .NET Standard:

![image](https://user-images.githubusercontent.com/15019084/35990032-79fd3f7e-0d0b-11e8-9e89-383854a8b82b.png)

Can someone please help clear this up?

Thanks!

**Comment by borrrden** [comment]
.NET Standard 2.0 is unique in that it will attempt to use compatibility shins to consume a library written for .NET framework to unblock devs waiting for a downstream library to update. The warning text speaks for itself saying “we tried but this might not work”

1.x has no direct .net Standard support. Also in the future please ask questions on the forums instead of opening a github issue.
